/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Status */
        get: operations["data_status_api_v1_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Sync */
        post: operations["start_sync_api_v1_sync_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-runs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Sync */
        get: operations["current_sync_api_v1_sync_runs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-runs/current/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Current Sync */
        post: operations["cancel_current_sync_api_v1_sync_runs_current_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History Summary */
        get: operations["history_summary_api_v1_history_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/bands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History Bands */
        get: operations["history_bands_api_v1_history_bands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/misses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History Misses */
        get: operations["history_misses_api_v1_history_misses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/open-markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Markets */
        get: operations["open_markets_api_v1_open_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/open-markets/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Market Link */
        get: operations["open_market_link_api_v1_open_markets_link_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Band */
        Band: {
            /** Min Percent */
            min_percent: number;
            /** Max Percent */
            max_percent: number;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** BandsResponse */
        BandsResponse: {
            /** Items */
            items: components["schemas"]["Band"][];
        };
        /** DataStatus */
        DataStatus: {
            /** Has Data */
            has_data: boolean;
            /** Coverage Start */
            coverage_start?: string | null;
            /** Coverage End */
            coverage_end?: string | null;
            /** Last Successful Sync */
            last_successful_sync?: string | null;
            /**
             * Total Markets
             * @default 0
             */
            total_markets: number;
            /**
             * Total Trades
             * @default 0
             */
            total_trades: number;
            /**
             * Aggregate Markets
             * @default 0
             */
            aggregate_markets: number;
            /**
             * Raw Markets
             * @default 0
             */
            raw_markets: number;
            /**
             * Raw Trades
             * @default 0
             */
            raw_trades: number;
            /**
             * Dataset Version
             * @default 2
             */
            dataset_version: string;
            /**
             * Scope
             * @default empty
             */
            scope: string;
            /**
             * Mve Excluded
             * @default true
             */
            mve_excluded: boolean;
            /** Legacy Cache Error */
            legacy_cache_error?: string | null;
            /**
             * Storage Bytes
             * @default 0
             */
            storage_bytes: number;
            /** Storage Limit Bytes */
            storage_limit_bytes?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistorySummary */
        HistorySummary: {
            window: components["schemas"]["Window"];
            /** Threshold */
            threshold: number;
            /** Settled Markets */
            settled_markets: number;
            /** Crossed Markets */
            crossed_markets: number;
            /** Wrong Markets */
            wrong_markets: number;
            /** Miss Rate */
            miss_rate: number | null;
        };
        /** Miss */
        Miss: {
            /** Ticker */
            ticker: string;
            /** Event Ticker */
            event_ticker?: string | null;
            /** Title */
            title: string;
            /** Peak Confidence */
            peak_confidence: number;
            /** Losing Side */
            losing_side: string;
            /** First Crossed At */
            first_crossed_at?: string | null;
            /**
             * Settled At
             * Format: date-time
             */
            settled_at: string;
        };
        /** MissesResponse */
        MissesResponse: {
            /** Items */
            items: components["schemas"]["Miss"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
        };
        /** OpenMarket */
        OpenMarket: {
            /** Ticker */
            ticker: string;
            /** Event Ticker */
            event_ticker?: string | null;
            /**
             * Category
             * @default Other
             */
            category: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /**
             * Qualifying Side
             * @enum {string}
             */
            qualifying_side: "yes" | "no" | "both";
            /** Qualifying Label */
            qualifying_label: string;
            /** Qualifying Bid Percent */
            qualifying_bid_percent: number;
            /** Yes Bid Percent */
            yes_bid_percent?: number | null;
            /** No Bid Percent */
            no_bid_percent?: number | null;
            /** Volume 24H */
            volume_24h?: number | null;
            /** Liquidity Dollars */
            liquidity_dollars?: number | null;
            /**
             * Close At
             * Format: date-time
             */
            close_at: string;
            /**
             * Can Close Early
             * @default false
             */
            can_close_early: boolean;
        };
        /**
         * OpenMarketHorizon
         * @enum {string}
         */
        OpenMarketHorizon: "24h" | "3d" | "7d" | "14d";
        /**
         * OpenMarketLink
         * @description The canonical Kalshi event page containing a selected market.
         */
        OpenMarketLink: {
            /** Url */
            url: string;
        };
        /** OpenMarketsError */
        OpenMarketsError: {
            /**
             * Code
             * @default open_markets_unavailable
             * @constant
             */
            code: "open_markets_unavailable";
            /** Message */
            message: string;
            /**
             * Resumable
             * @default true
             */
            resumable: boolean;
        };
        /** OpenMarketsErrorResponse */
        OpenMarketsErrorResponse: {
            error: components["schemas"]["OpenMarketsError"];
            /** Breaker Seconds Remaining */
            breaker_seconds_remaining: number;
        };
        /**
         * OpenMarketsResponse
         * @description A non-persistent, point-in-time view of qualifying open contracts.
         */
        OpenMarketsResponse: {
            /** Items */
            items: components["schemas"]["OpenMarket"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Pages */
            pages: number;
            /** Scanned Markets */
            scanned_markets: number;
            /** Matching Markets */
            matching_markets: number;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Refresh State */
            refresh_state: string;
            /** Breaker Seconds Remaining */
            breaker_seconds_remaining: number;
            /** Next Close At */
            next_close_at?: string | null;
            /** Highest Bid */
            highest_bid?: number | null;
        };
        /** SyncRequest */
        SyncRequest: {
            /** @default 6m */
            window: components["schemas"]["Window"];
        };
        /** SyncRun */
        SyncRun: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Stage */
            stage: string;
            window: components["schemas"]["Window"];
            /**
             * Processed Markets
             * @default 0
             */
            processed_markets: number;
            /**
             * Total Markets
             * @default 0
             */
            total_markets: number;
            /**
             * Progress Percent
             * @default 0
             */
            progress_percent: number;
            /**
             * Raw Markets
             * @default 0
             */
            raw_markets: number;
            /**
             * Raw Trades
             * @default 0
             */
            raw_trades: number;
            /**
             * Breaker Open
             * @default false
             */
            breaker_open: boolean;
            /**
             * Breaker Seconds Remaining
             * @default 0
             */
            breaker_seconds_remaining: number;
            /** Error */
            error?: string | null;
            /**
             * Resumable
             * @default false
             */
            resumable: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Window
         * @enum {string}
         */
        Window: "3m" | "6m" | "1y" | "all";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    data_status_api_v1_data_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStatus"];
                };
            };
        };
    };
    start_sync_api_v1_sync_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_sync_api_v1_sync_runs_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRun"] | null;
                };
            };
        };
    };
    cancel_current_sync_api_v1_sync_runs_current_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRun"] | null;
                };
            };
        };
    };
    history_summary_api_v1_history_summary_get: {
        parameters: {
            query?: {
                window?: components["schemas"]["Window"];
                threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_bands_api_v1_history_bands_get: {
        parameters: {
            query?: {
                window?: components["schemas"]["Window"];
                threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BandsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_misses_api_v1_history_misses_get: {
        parameters: {
            query?: {
                window?: components["schemas"]["Window"];
                threshold?: number;
                min_percent?: number | null;
                max_percent?: number | null;
                page?: number;
                page_size?: number;
                sort?: string;
                direction?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_markets_api_v1_open_markets_get: {
        parameters: {
            query?: {
                threshold?: number;
                horizon?: components["schemas"]["OpenMarketHorizon"];
                page?: number;
                page_size?: number;
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenMarketsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Live snapshot temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenMarketsErrorResponse"];
                };
            };
        };
    };
    open_market_link_api_v1_open_markets_link_get: {
        parameters: {
            query: {
                event_ticker: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenMarketLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
